# Generated by Django 5.1.6 on 2025-05-12 07:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "announcement_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="公告訊息編號"
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("系統公告", "系統公告"),
                            ("促銷活動", "促銷活動"),
                            ("政策變更", "政策變更"),
                            ("其他", "其他"),
                        ],
                        default="系統公告",
                        max_length=10,
                        verbose_name="公告類型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("content", models.TextField(verbose_name="公告內容")),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="開始時間"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="結束時間"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "公告訊息",
                "verbose_name_plural": "公告訊息",
                "db_table": "announcements",
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "category_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品分類編號"
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="商品分類名稱"
                    ),
                ),
            ],
            options={
                "verbose_name": "分類",
                "verbose_name_plural": "分類",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="MembershipLevels",
            fields=[
                (
                    "level_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="會員等級編號"
                    ),
                ),
                (
                    "level_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="會員等級名稱"
                    ),
                ),
                (
                    "min_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低消費",
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="折扣比率(%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "會員等級",
                "verbose_name_plural": "會員等級",
                "db_table": "membership_levels",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="訂單編號"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="訂單號碼"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=100, verbose_name="收件人姓名"),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=20, verbose_name="收件人電話"),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="電子郵件"
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("宅配", "宅配"),
                            ("超商取貨", "超商取貨"),
                            ("郵寄", "郵寄"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="寄送方式",
                    ),
                ),
                ("shipping_address", models.TextField(verbose_name="寄送地址")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("信用卡", "信用卡"),
                            ("ATM", "ATM"),
                            ("貨到付款", "貨到付款"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="付款方式",
                    ),
                ),
                (
                    "total_price",
                    models.IntegerField(default=0, verbose_name="商品總金額"),
                ),
                (
                    "discount_amount",
                    models.IntegerField(default=0, verbose_name="折扣金額"),
                ),
                ("shipping_fee", models.IntegerField(default=0, verbose_name="運費")),
                (
                    "final_price",
                    models.IntegerField(default=0, verbose_name="最終應付金額"),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("待付款", "待付款"),
                            ("已付款", "已付款"),
                            ("已出貨", "已出貨"),
                            ("已完成", "已完成"),
                            ("已取消", "已取消"),
                            ("退貨中", "退貨中"),
                            ("已退貨", "已退貨"),
                        ],
                        default="待付款",
                        max_length=10,
                        verbose_name="訂單狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "status_updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "訂單",
                "verbose_name_plural": "訂單",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="PackageTypes",
            fields=[
                (
                    "package_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="包裝類型編號"
                    ),
                ),
                (
                    "package_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="包裝類型"
                    ),
                ),
            ],
            options={
                "verbose_name": "包裝類型",
                "verbose_name_plural": "包裝類型",
                "db_table": "package_types",
            },
        ),
        migrations.CreateModel(
            name="ProductEffectiveness",
            fields=[
                (
                    "effectiveness_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品功效編號"
                    ),
                ),
                (
                    "effectiveness_name",
                    models.CharField(max_length=50, unique=True, verbose_name="功效"),
                ),
            ],
            options={
                "verbose_name": "功效",
                "verbose_name_plural": "功效",
                "db_table": "product_effectiveness",
            },
        ),
        migrations.CreateModel(
            name="ProductFragrances",
            fields=[
                (
                    "fragrance_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品香味編號"
                    ),
                ),
                (
                    "fragrance_name",
                    models.CharField(max_length=100, unique=True, verbose_name="香味"),
                ),
            ],
            options={
                "verbose_name": "商品香味",
                "verbose_name_plural": "商品香味",
                "db_table": "product_fragrances",
            },
        ),
        migrations.CreateModel(
            name="ProductIngredients",
            fields=[
                (
                    "ingredient_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品成分編號"
                    ),
                ),
                (
                    "ingredient_name",
                    models.CharField(max_length=100, unique=True, verbose_name="成分"),
                ),
            ],
            options={
                "verbose_name": "成分",
                "verbose_name_plural": "成分",
                "db_table": "product_ingredients",
            },
        ),
        migrations.CreateModel(
            name="ProductOrigins",
            fields=[
                (
                    "origin_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品產地編號"
                    ),
                ),
                (
                    "origin_name",
                    models.CharField(max_length=100, unique=True, verbose_name="產地"),
                ),
            ],
            options={
                "verbose_name": "商品產地",
                "verbose_name_plural": "商品產地",
                "db_table": "product_origins",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "product_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品編號"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="商品名稱")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="商品描述(短)"
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="商品描述(長)"
                    ),
                ),
                (
                    "suitable_for",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="適用於"
                    ),
                ),
                (
                    "usage_instructions",
                    models.TextField(blank=True, null=True, verbose_name="使用方式"),
                ),
                (
                    "shelf_life",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="保存期限(月)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductSizes",
            fields=[
                (
                    "size_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品容量編號"
                    ),
                ),
                (
                    "size_value",
                    models.CharField(max_length=50, unique=True, verbose_name="容量"),
                ),
            ],
            options={
                "verbose_name": "商品容量",
                "verbose_name_plural": "商品容量",
                "db_table": "product_sizes",
            },
        ),
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "supplier_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="供應商編號"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="供應商名稱"
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="電話")),
                ("address", models.TextField(verbose_name="地址")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "供應商",
                "verbose_name_plural": "供應商",
                "db_table": "suppliers",
            },
        ),
        migrations.CreateModel(
            name="ProductVariants",
            fields=[
                (
                    "variant_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="商品規格變體編號",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="價格")),
                (
                    "is_gift",
                    models.BooleanField(default=False, verbose_name="是否為贈品"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "fragrance",
                    models.ForeignKey(
                        blank=True,
                        db_column="fragrance_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productfragrances",
                        verbose_name="香氣",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        db_column="origin_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productorigins",
                        verbose_name="產地",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        db_column="package_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.packagetypes",
                        verbose_name="包裝類型",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.products",
                        verbose_name="商品名稱",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        db_column="size_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productsizes",
                        verbose_name="商品容量",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品和規格",
                "verbose_name_plural": "商品和規格",
                "db_table": "product_variants",
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "image_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品圖片編號"
                    ),
                ),
                (
                    "image_name",
                    models.CharField(max_length=50, verbose_name="圖片名稱"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="排列順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productvariants",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品圖片",
                "verbose_name_plural": "商品圖片",
                "db_table": "product_images",
            },
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "order_item_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="訂單詳情編號"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="數量")),
                ("price", models.IntegerField(verbose_name="價格")),
                ("subtotal", models.IntegerField(verbose_name="小計")),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.orders",
                        verbose_name="訂單",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productvariants",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單詳情",
                "verbose_name_plural": "訂單詳情",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="Promotions",
            fields=[
                (
                    "promo_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="活動編號"
                    ),
                ),
                (
                    "promo_name",
                    models.CharField(max_length=255, verbose_name="活動名稱"),
                ),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[("活動", "活動"), ("優惠券", "優惠券")],
                        max_length=10,
                        verbose_name="活動類型",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("百分比折扣", "百分比折扣"),
                            ("固定金額折扣", "固定金額折扣"),
                            ("贈品", "贈品"),
                        ],
                        max_length=10,
                        verbose_name="折扣類型",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="折扣金額或折扣比率",
                    ),
                ),
                (
                    "minimum_spending",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最低消費金額門檻"
                    ),
                ),
                (
                    "trigger_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="需要達成的購買數量"
                    ),
                ),
                ("conditions", models.TextField(verbose_name="活動描述")),
                (
                    "apply_method",
                    models.CharField(
                        choices=[("自動套用", "自動套用"), ("優惠碼", "優惠碼")],
                        max_length=10,
                        verbose_name="套用類型",
                    ),
                ),
                (
                    "promo_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="優惠碼",
                    ),
                ),
                (
                    "receive_method",
                    models.CharField(
                        blank=True,
                        choices=[("先發放", "先發放"), ("自由輸入", "自由輸入")],
                        max_length=10,
                        null=True,
                        verbose_name="優惠碼取得方式",
                    ),
                ),
                (
                    "is_vip_only",
                    models.BooleanField(
                        default=False, verbose_name="是否為會員等級折扣"
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="總使用次數限制"
                    ),
                ),
                (
                    "per_user_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="每個會員限制使用次數"
                    ),
                ),
                (
                    "is_accumulative_discount",
                    models.BooleanField(default=False, verbose_name="是否允許累積折扣"),
                ),
                (
                    "is_accumulative_gift",
                    models.BooleanField(default=False, verbose_name="是否允許累積贈品"),
                ),
                ("start_date", models.DateTimeField(verbose_name="活動開始時間")),
                ("end_date", models.DateTimeField(verbose_name="活動結束時間")),
                (
                    "target_levels",
                    models.ManyToManyField(
                        blank=True,
                        to="myapp.membershiplevels",
                        verbose_name="適用會員等級",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動",
                "verbose_name_plural": "活動",
                "db_table": "promotions",
            },
        ),
        migrations.CreateModel(
            name="PromotionImages",
            fields=[
                (
                    "image_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="活動圖片編號"
                    ),
                ),
                (
                    "image_name",
                    models.CharField(max_length=255, verbose_name="圖片名稱"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="排列順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        db_column="promo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.promotions",
                        verbose_name="活動",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動圖片",
                "verbose_name_plural": "活動圖片",
                "db_table": "promotion_images",
            },
        ),
        migrations.CreateModel(
            name="OrderAppliedPromotions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "自動套用"), ("coupon", "優惠碼")],
                        max_length=10,
                        verbose_name="優惠套用方式",
                    ),
                ),
                (
                    "discount_amount",
                    models.IntegerField(default=0, verbose_name="折扣金額"),
                ),
                (
                    "gift_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="贈品數量"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.orders",
                        verbose_name="訂單",
                    ),
                ),
                (
                    "gift_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.productvariants",
                        verbose_name="贈品",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.promotions",
                        verbose_name="活動",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單優惠",
                "verbose_name_plural": "訂單優惠",
                "db_table": "order_applied_promotions",
            },
        ),
        migrations.CreateModel(
            name="RecommendedProducts",
            fields=[
                (
                    "recommendation_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="推薦商品編號"
                    ),
                ),
                (
                    "recommended_for",
                    models.CharField(
                        choices=[
                            ("所有用戶", "所有用戶"),
                            ("特定會員", "特定會員"),
                            ("熱門商品", "熱門商品"),
                        ],
                        max_length=10,
                        verbose_name="推薦對象",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productvariants",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "推薦商品",
                "verbose_name_plural": "推薦商品",
                "db_table": "recommended_products",
            },
        ),
        migrations.CreateModel(
            name="StockIn",
            fields=[
                (
                    "stock_in_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="進貨紀錄及庫存編號",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="進貨數量")),
                ("purchase_price", models.IntegerField(verbose_name="進貨價格")),
                (
                    "received_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="進貨日期"),
                ),
                (
                    "expiration_date",
                    models.DateField(blank=True, null=True, verbose_name="有效期限"),
                ),
                (
                    "remaining_quantity",
                    models.IntegerField(verbose_name="該批次剩餘庫存數量"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productvariants",
                        verbose_name="商品",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.suppliers",
                        verbose_name="廠商",
                    ),
                ),
            ],
            options={
                "verbose_name": "進貨紀錄及庫存",
                "verbose_name_plural": "進貨紀錄及庫存",
                "db_table": "stock_in",
            },
        ),
        migrations.AddField(
            model_name="products",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                db_column="supplier_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.suppliers",
                verbose_name="供應商",
            ),
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="會員編號"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="電話",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="地址"),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("男", "男"), ("女", "女"), ("其他", "其他")],
                        max_length=10,
                        null=True,
                        verbose_name="性別",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        db_column="level_id",
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.membershiplevels",
                        verbose_name="會員等級",
                    ),
                ),
            ],
            options={
                "verbose_name": "會員",
                "verbose_name_plural": "會員",
                "db_table": "users",
            },
        ),
        migrations.AddField(
            model_name="orders",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.users",
                verbose_name="會員",
            ),
        ),
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                (
                    "feedback_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="意見回饋編號"
                    ),
                ),
                (
                    "feedback_category",
                    models.CharField(
                        choices=[
                            ("網站問題", "網站問題"),
                            ("商品問題", "商品問題"),
                            ("配送問題", "配送問題"),
                            ("客服問題", "客服問題"),
                            ("其他", "其他"),
                        ],
                        default="其他",
                        max_length=10,
                        verbose_name="意見分類",
                    ),
                ),
                ("feedback_text", models.TextField(verbose_name="回饋內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                        verbose_name="會員",
                    ),
                ),
            ],
            options={
                "verbose_name": "意見回饋",
                "verbose_name_plural": "意見回饋",
                "db_table": "feedbacks",
            },
        ),
        migrations.CreateModel(
            name="AuthUsers",
            fields=[
                (
                    "auth_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="會員帳號密碼編號",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="會員名稱"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="電子郵件"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密碼")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                        verbose_name="會員",
                    ),
                ),
            ],
            options={
                "verbose_name": "會員帳號密碼",
                "verbose_name_plural": "會員帳號密碼",
                "db_table": "auth_users",
            },
        ),
        migrations.CreateModel(
            name="ProductIngredientsMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        db_column="ingredient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productingredients",
                        verbose_name="成分",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.products",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品成分",
                "verbose_name_plural": "商品成分",
                "db_table": "product_ingredients_map",
                "unique_together": {("product", "ingredient")},
            },
        ),
        migrations.CreateModel(
            name="ProductEffectivenessMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effectiveness",
                    models.ForeignKey(
                        db_column="effectiveness_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.producteffectiveness",
                        verbose_name="功效",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.products",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品功效",
                "verbose_name_plural": "商品功效",
                "db_table": "product_effectiveness_map",
                "unique_together": {("product", "effectiveness")},
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.categories",
                        verbose_name="商品分類",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.products",
                        verbose_name="商品名稱",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分類",
                "verbose_name_plural": "商品分類",
                "db_table": "product_category",
                "unique_together": {("product", "category")},
            },
        ),
        migrations.CreateModel(
            name="PromotionGifts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift_quantity",
                    models.IntegerField(default=1, verbose_name="贈品數"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productvariants",
                        verbose_name="商品",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        db_column="promo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.promotions",
                        verbose_name="活動",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動贈品",
                "verbose_name_plural": "活動贈品",
                "db_table": "promotion_gifts",
                "unique_together": {("promo", "variant")},
            },
        ),
        migrations.CreateModel(
            name="PromotionTargetCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.categories",
                        verbose_name="分類",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        db_column="promo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.promotions",
                        verbose_name="活動",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動限定分類",
                "verbose_name_plural": "活動限定分類",
                "db_table": "promotion_target_categories",
                "unique_together": {("promo", "category")},
            },
        ),
        migrations.CreateModel(
            name="PromotionTargetVariants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        db_column="promo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.promotions",
                        verbose_name="活動",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productvariants",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動限定商品",
                "verbose_name_plural": "活動限定商品",
                "db_table": "promotion_target_variants",
                "unique_together": {("promo", "variant")},
            },
        ),
        migrations.CreateModel(
            name="UserPromotions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後使用時間"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次數"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="有效起始時間"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="有效結束時間"
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        db_column="promo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.promotions",
                        verbose_name="活動",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                        verbose_name="會員",
                    ),
                ),
            ],
            options={
                "verbose_name": "會員優惠",
                "verbose_name_plural": "會員優惠",
                "db_table": "user_promotions",
                "unique_together": {("user", "promo")},
            },
        ),
        migrations.CreateModel(
            name="ProductReviews",
            fields=[
                (
                    "review_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品評價編號"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="評價",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(blank=True, null=True, verbose_name="評價內容"),
                ),
                (
                    "review_image",
                    models.TextField(blank=True, null=True, verbose_name="圖片"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.orders",
                        verbose_name="訂單",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        db_column="variant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productvariants",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                        verbose_name="會員",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品評價",
                "verbose_name_plural": "商品評價",
                "db_table": "product_reviews",
                "unique_together": {("order", "user", "variant")},
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="追蹤日期"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.productvariants",
                        verbose_name="追蹤商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                        verbose_name="商品追蹤編號",
                    ),
                ),
            ],
            options={
                "verbose_name": "我的最愛",
                "verbose_name_plural": "我的最愛",
                "db_table": "favorite",
                "unique_together": {("user", "variant")},
            },
        ),
    ]
